# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/Image_Info.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 667)
        MainWindow.setStyleSheet("background-color: rgb(50, 62, 72);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 811, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("gui/../assets/Logo.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 100, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(530, 100, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_3.setObjectName("label_3")
        self.front = QtWidgets.QLabel(self.centralwidget)
        self.front.setGeometry(QtCore.QRect(30, 140, 341, 131))
        self.front.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.front.setStyleSheet("QLabel{border : 1px solid grey;}")
        self.front.setObjectName("front")
        self.rear = QtWidgets.QLabel(self.centralwidget)
        self.rear.setGeometry(QtCore.QRect(420, 140, 341, 131))
        self.rear.setStyleSheet("QLabel{border : 1px solid grey;}")
        self.rear.setObjectName("rear")
        self.front_debug = QtWidgets.QGroupBox(self.centralwidget)
        self.front_debug.setGeometry(QtCore.QRect(60, 300, 271, 251))
        self.front_debug.setStyleSheet("color: rgb(238, 238, 236);")
        self.front_debug.setObjectName("front_debug")
        self.rear_debug = QtWidgets.QGroupBox(self.centralwidget)
        self.rear_debug.setGeometry(QtCore.QRect(460, 300, 271, 251))
        self.rear_debug.setStyleSheet("color: rgb(238, 238, 236);")
        self.rear_debug.setObjectName("rear_debug")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 590, 151, 40))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Image-Info", "Image-Info"))
        self.label_2.setText(_translate("MainWindow", "Front_View"))
        self.label_3.setText(_translate("MainWindow", "Rear View"))
        self.front_debug.setTitle(_translate("MainWindow", "             Front View - Debug Info"))
        self.rear_debug.setTitle(_translate("MainWindow", "               Rear View - Debug Info"))
        self.pushButton.setText(_translate("MainWindow", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
